# https://taskfile.dev

version: '3'

vars:
  MODULE: github.com/zcong1993/template-go-cli
  COVERPKG: ./...
  GOARCH: ''
  TEST_FLAGS: ''

tasks:
  test:
    deps:
      - setup:gotestsum
    cmds:
      - gotestsum --format testname -- {{.TEST_FLAGS}} {{.CLI_ARGS}}
    env:
      GOARCH: '{{.GOARCH}}'
  test:cov:
    deps:
      - setup:gotestsum
    cmds:
      - gotestsum --format testname -- {{.TEST_FLAGS}} -covermode=count -coverprofile=coverage.txt {{.CLI_ARGS}}
    env:
      GOARCH: '{{.GOARCH}}'
  coverage:
    cmds:
      - task: test:cov
        vars:
          CLI_ARGS: >-
            -coverpkg={{.COVERPKG}} ./... &&
            go tool cover -func coverage.txt | grep total

  lint:
    deps:
      - setup:golangci-lint
    cmds:
      - ./bin/golangci-lint run {{.CLI_ARGS}}

  lint:fast:
    cmds:
      - task: lint
        vars:
          CLI_ARGS: --fast {{.CLI_ARGS}}

  format:
    cmds:
      - task: goimports
        vars:
          CLI_ARGS: .

  goimports:
    deps:
      - setup:goimports
      - setup:goimportshack
    cmds:
      - >-
        ./bin/goimports.sh {{.CLI_ARGS}} &&
        ./bin/goimports -local '{{.MODULE}}' -w {{.CLI_ARGS}}

  setup:
    deps:
      - setup:local
    cmds:
      - go install github.com/evilmartians/lefthook@latest
      - lefthook install

  setup:force:
    cmds:
      - rm -rf ./bin
      - task: setup:local

  setup:golangci-lint:
    cmds:
      - >-
        curl -SL
        https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
        | sh -s v1.50.1
    status:
      - test -f ./bin/golangci-lint
      - ./bin/golangci-lint --version | grep -q ' 1.50.1 '
  setup:goimports:
    cmds:
      - GOBIN=`pwd`/bin go install golang.org/x/tools/cmd/goimports@v0.4.0
    status:
      - test -f ./bin/goimports
  setup:gotestsum:
    cmds:
      - GOBIN=`pwd`/bin go install gotest.tools/gotestsum@latest
    status:
      - test -f ./bin/gotestsum
  setup:goimportshack:
    cmds:
      - |
        cat >./bin/goimports.sh <<'EOL'
        #!/usr/bin/env sh

        if [ $# -eq 0 ]; then
          echo "usage: $0 <filename> <filename2>"
          echo "usage: $0 . # handle all files"
          exit 1
        fi

        FILES=("$@")

        if [ "$1" = "." ]; then
          echo "all go files"
          FILES=$(find . -name "*.go" | grep -v -e ".mock.go" -e ".gen.go" -e ".pb.go")
        fi

        for i in "${FILES[@]}"; do
          sed -i '' -e '
            /^import/,/)/ {
            /^$/ d
            }
          ' $i
        done

        EOL
      - chmod +x ./bin/goimports.sh
    status:
      - test -f ./bin/goimports.sh

  setup:local:
    deps:
      - setup:golangci-lint
      - setup:goimports
      - setup:gotestsum
      - setup:goimportshack
